#pragma once

#include <vulkan/vulkan.h>
#include <vk_mem_alloc.h>
#include <string>
#include <unordered_map>
#include <vector>
#include <memory>
#include <glm/glm.hpp>

namespace Core {
    namespace RHI { class VulkanContext; }
namespace UI {

    /// @brief Metrics for a single glyph in the font atlas
    struct GlyphMetrics {
        uint32_t unicode = 0;           ///< Unicode code point
        float advance = 0.0f;           ///< Horizontal advance after glyph (in em units)
        
        // Plane bounds (in em units, relative to baseline)
        float planeLeft = 0.0f;
        float planeBottom = 0.0f;
        float planeRight = 0.0f;
        float planeTop = 0.0f;
        
        // Atlas bounds (normalized UV coordinates 0-1)
        float atlasLeft = 0.0f;
        float atlasBottom = 0.0f;
        float atlasRight = 0.0f;
        float atlasTop = 0.0f;
    };

    /// @brief Kerning pair for specific character combinations
    struct KerningPair {
        uint32_t first = 0;             ///< First character unicode
        uint32_t second = 0;            ///< Second character unicode
        float advance = 0.0f;           ///< Kerning adjustment (in em units)
    };

    /// @brief Font atlas metadata from MSDF atlas generator
    struct FontAtlasMetrics {
        std::string name;
        float emSize = 0.0f;            ///< Em size used during atlas generation
        float lineHeight = 0.0f;        ///< Line height (in em units)
        float ascender = 0.0f;          ///< Ascender height (in em units)
        float descender = 0.0f;         ///< Descender depth (in em units, negative)
        float underlineY = 0.0f;        ///< Underline position
        float underlineThickness = 0.0f;
        
        uint32_t atlasWidth = 0;        ///< Atlas texture width
        uint32_t atlasHeight = 0;       ///< Atlas texture height
        std::string atlasType;          ///< "msdf", "mtsdf", "sdf"
        float distanceRange = 0.0f;     ///< Signed distance range in pixels
    };

    /// @brief Manages a single font atlas (texture + glyph metrics)
    /// 
    /// FontAtlas loads and manages MSDF font atlases generated by msdf-atlas-gen.
    /// It provides glyph lookup, kerning support, and atlas texture access.
    class FontAtlas {
    public:
        FontAtlas() = default;
        ~FontAtlas();

        // Disable copy, allow move
        FontAtlas(const FontAtlas&) = delete;
        FontAtlas& operator=(const FontAtlas&) = delete;
        FontAtlas(FontAtlas&& other) noexcept;
        FontAtlas& operator=(FontAtlas&& other) noexcept;

        /// @brief Load font atlas from MSDF-generated files
        /// @param atlasPath Path to atlas image file (PNG)
        /// @param metricsPath Path to atlas JSON metrics file
        /// @param vulkanContext Vulkan context for texture creation
        /// @return true if loading succeeded
        bool Load(const std::string& atlasPath, const std::string& metricsPath,
                  RHI::VulkanContext* vulkanContext);

        /// @brief Release all resources
        void Unload();

        /// @brief Check if atlas is loaded
        bool IsLoaded() const { return m_Loaded; }

        /// @brief Get glyph metrics for a unicode character
        /// @param unicode The unicode code point
        /// @return Pointer to glyph metrics, or nullptr if not found
        const GlyphMetrics* GetGlyph(uint32_t unicode) const;

        /// @brief Get kerning adjustment between two characters
        /// @param first First character unicode
        /// @param second Second character unicode
        /// @return Kerning adjustment in em units (0 if no kerning defined)
        float GetKerning(uint32_t first, uint32_t second) const;

        /// @brief Get atlas metrics
        const FontAtlasMetrics& GetMetrics() const { return m_Metrics; }

        /// @brief Get atlas texture image
        VkImage GetAtlasImage() const { return m_AtlasImage; }

        /// @brief Get atlas texture image view
        VkImageView GetAtlasImageView() const { return m_AtlasImageView; }

        /// @brief Get atlas texture sampler
        VkSampler GetAtlasSampler() const { return m_AtlasSampler; }

        /// @brief Calculate text width in em units
        /// @param text UTF-8 encoded text
        /// @return Width of the text in em units
        float CalculateTextWidth(std::string_view text) const;

        /// @brief Get the font name
        const std::string& GetName() const { return m_Metrics.name; }

    private:
        /// @brief Parse JSON metrics file
        bool ParseMetrics(const std::string& metricsPath);

        /// @brief Create Vulkan texture from atlas image
        bool CreateAtlasTexture(const std::string& atlasPath, RHI::VulkanContext* vulkanContext);

        /// @brief Destroy Vulkan resources
        void DestroyVulkanResources();

        /// @brief Generate kerning key from two unicodes
        static uint64_t KerningKey(uint32_t first, uint32_t second) {
            return (static_cast<uint64_t>(first) << 32) | second;
        }

    private:
        bool m_Loaded = false;
        RHI::VulkanContext* m_VulkanContext = nullptr;

        FontAtlasMetrics m_Metrics;
        std::unordered_map<uint32_t, GlyphMetrics> m_Glyphs;
        std::unordered_map<uint64_t, float> m_Kerning;

        // Vulkan resources
        VkImage m_AtlasImage = VK_NULL_HANDLE;
        VmaAllocation m_AtlasAllocation = VK_NULL_HANDLE;
        VkImageView m_AtlasImageView = VK_NULL_HANDLE;
        VkSampler m_AtlasSampler = VK_NULL_HANDLE;
    };

    /// @brief Manager for multiple font atlases
    class FontManager {
    public:
        static FontManager& Get();

        /// @brief Initialize with Vulkan context
        void Initialize(RHI::VulkanContext* vulkanContext);

        /// @brief Shutdown and release all atlases
        void Shutdown();

        /// @brief Load a font atlas
        /// @param name Name to reference the font (e.g., "default", "title", "mono")
        /// @param atlasPath Path to atlas PNG
        /// @param metricsPath Path to atlas JSON
        /// @return true if loading succeeded
        bool LoadFont(const std::string& name, const std::string& atlasPath,
                      const std::string& metricsPath);

        /// @brief Get a loaded font atlas
        /// @param name Font name
        /// @return Pointer to font atlas, or nullptr if not found
        FontAtlas* GetFont(const std::string& name);

        /// @brief Get the default font atlas
        FontAtlas* GetDefaultFont();

        /// @brief Check if a font is loaded
        bool HasFont(const std::string& name) const;

        /// @brief Set the default font name
        void SetDefaultFont(const std::string& name) { m_DefaultFontName = name; }

    private:
        FontManager() = default;
        ~FontManager() = default;

        RHI::VulkanContext* m_VulkanContext = nullptr;
        std::unordered_map<std::string, std::unique_ptr<FontAtlas>> m_Fonts;
        std::string m_DefaultFontName = "default";
    };

} // namespace UI
} // namespace Core
